CREATE TABLE shopily_item_list (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    code TEXT NOT NULL UNIQUE,
    product_name TEXT NOT NULL,
    aisle INTEGER NOT NULL,
    supermarket_id INTEGER
        REFERENCES shopily_supermarkets(id) ON DELETE SET NULL,
    date_created TIMESTAMP NOT NULL DEFAULT now()
);